[package]
name = "idx_fixed_store"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", features = [ "small_rng" ] }
log = "0.4"
env_logger = "0.10"
common = { path = "../../common" }
txn_manager = { path = "../../txn_manager" }
